// Hand-authored source data for the deterministic seed (ADR-001).
// Neighborhoods are real places with approximate coordinates so pins land
// somewhere plausible; every store, address, and phone number is fictional.

import { type Attribute } from "@/lib/types/store";

export const BRAND = "Cedar & Main Outfitters";

/** Fixed RNG seed — the whole dataset is a pure function of this value. */
export const SEED = 20260704;

// The catalog is data, not schema (ADR-001): this list seeds the
// `attributes` table, which then feeds the AI enum and the UI filters.
export const ATTRIBUTE_CATALOG: readonly Attribute[] = [
  { slug: "mens-department", label: "Men's department", category: "department" },
  { slug: "womens-department", label: "Women's department", category: "department" },
  { slug: "kids-department", label: "Kids' department", category: "department" },
  { slug: "footwear", label: "Footwear", category: "department" },
  { slug: "outdoor-gear", label: "Outdoor gear", category: "department" },
  { slug: "curbside-pickup", label: "Curbside pickup", category: "service" },
  {
    slug: "buy-online-pickup-in-store",
    label: "Buy online, pick up in store",
    category: "service",
  },
  { slug: "alterations", label: "Alterations & tailoring", category: "service" },
  { slug: "personal-styling", label: "Personal styling", category: "service" },
  { slug: "wheelchair-accessible", label: "Wheelchair accessible", category: "amenity" },
  { slug: "ev-charging", label: "EV charging", category: "amenity" },
  { slug: "pet-friendly", label: "Pet friendly", category: "amenity" },
  { slug: "free-parking", label: "Free parking", category: "parking" },
  { slug: "parking-garage", label: "Parking garage", category: "parking" },
  { slug: "street-parking", label: "Street parking", category: "parking" },
] as const;

/**
 * Probability that a store carries each non-parking attribute.
 * Parking is assigned separately (exactly one, weighted by store kind).
 */
export const ATTRIBUTE_PROBABILITY: Readonly<Record<string, number>> = {
  "mens-department": 0.84,
  "womens-department": 0.92,
  "kids-department": 0.55,
  footwear: 0.75,
  "outdoor-gear": 0.4,
  "curbside-pickup": 0.65,
  "buy-online-pickup-in-store": 0.8,
  alterations: 0.35,
  "personal-styling": 0.2,
  "wheelchair-accessible": 0.95,
  "ev-charging": 0.25,
  "pet-friendly": 0.3,
};

export type StoreKind = "urban" | "suburban";

/** Exactly one parking attribute per store, weighted by neighborhood kind. */
export const PARKING_WEIGHTS: Readonly<
  Record<StoreKind, ReadonlyArray<readonly [slug: string, weight: number]>>
> = {
  urban: [
    ["street-parking", 0.5],
    ["parking-garage", 0.45],
    ["free-parking", 0.05],
  ],
  suburban: [
    ["free-parking", 0.85],
    ["parking-garage", 0.1],
    ["street-parking", 0.05],
  ],
};

export interface HoursPattern {
  slug: string;
  urbanWeight: number;
  suburbanWeight: number;
  /** Index 0 = Sunday … 6 = Saturday; null = closed that day. */
  days: ReadonlyArray<readonly [opensAt: string, closesAt: string] | null>;
}

const MON_SAT = (open: string, close: string) =>
  Array.from({ length: 6 }, () => [open, close] as const);

export const HOURS_PATTERNS: readonly HoursPattern[] = [
  {
    slug: "standard",
    urbanWeight: 0.25,
    suburbanWeight: 0.4,
    days: [["11:00", "18:00"], ...MON_SAT("10:00", "21:00")],
  },
  {
    slug: "mall",
    urbanWeight: 0.05,
    suburbanWeight: 0.3,
    days: [["12:00", "18:00"], ...MON_SAT("10:00", "21:00")],
  },
  {
    slug: "late",
    urbanWeight: 0.2,
    suburbanWeight: 0.15,
    days: [["11:00", "19:00"], ...MON_SAT("10:00", "22:00")],
  },
  {
    slug: "downtown",
    urbanWeight: 0.35,
    suburbanWeight: 0.03,
    days: [null, ...MON_SAT("09:00", "19:00").slice(0, 5), ["10:00", "18:00"]],
  },
  {
    slug: "compact",
    urbanWeight: 0.15,
    suburbanWeight: 0.12,
    days: [null, ...MON_SAT("10:00", "19:00")],
  },
];

export const STREET_NAMES: readonly string[] = [
  "Main St",
  "High St",
  "Market St",
  "Maple Ave",
  "Oak St",
  "Washington Blvd",
  "Park Ave",
  "Lakeview Dr",
  "Mill Rd",
  "Center St",
  "Broad St",
  "College Ave",
];

export interface Neighborhood {
  /** Display name; also the store's name suffix and part of its slug. */
  area: string;
  /** Mailing city (core-city neighborhoods use the metro city). */
  city: string;
  state: string;
  postalCode: string;
  latitude: number;
  longitude: number;
  kind: StoreKind;
  /** Overrides the metro default (e.g. Kentucky and Chicagoland codes). */
  areaCode?: string;
}

export interface Metro {
  name: string;
  areaCode: string;
  timezone: string;
  neighborhoods: readonly Neighborhood[];
}

export const METROS: readonly Metro[] = [
  {
    name: "Columbus",
    areaCode: "614",
    timezone: "America/New_York",
    neighborhoods: [
      {
        area: "Short North",
        city: "Columbus",
        state: "OH",
        postalCode: "43201",
        latitude: 39.977,
        longitude: -83.004,
        kind: "urban",
      },
      {
        area: "Downtown",
        city: "Columbus",
        state: "OH",
        postalCode: "43215",
        latitude: 39.962,
        longitude: -83.001,
        kind: "urban",
      },
      {
        area: "German Village",
        city: "Columbus",
        state: "OH",
        postalCode: "43206",
        latitude: 39.943,
        longitude: -82.995,
        kind: "urban",
      },
      {
        area: "Grandview Heights",
        city: "Grandview Heights",
        state: "OH",
        postalCode: "43212",
        latitude: 39.98,
        longitude: -83.041,
        kind: "urban",
      },
      {
        area: "Clintonville",
        city: "Columbus",
        state: "OH",
        postalCode: "43214",
        latitude: 40.051,
        longitude: -83.02,
        kind: "urban",
      },
      {
        area: "Easton",
        city: "Columbus",
        state: "OH",
        postalCode: "43219",
        latitude: 40.051,
        longitude: -82.915,
        kind: "suburban",
      },
      {
        area: "Polaris",
        city: "Columbus",
        state: "OH",
        postalCode: "43240",
        latitude: 40.145,
        longitude: -82.982,
        kind: "suburban",
      },
      {
        area: "Dublin",
        city: "Dublin",
        state: "OH",
        postalCode: "43017",
        latitude: 40.099,
        longitude: -83.114,
        kind: "suburban",
      },
      {
        area: "Westerville",
        city: "Westerville",
        state: "OH",
        postalCode: "43081",
        latitude: 40.126,
        longitude: -82.929,
        kind: "suburban",
      },
      {
        area: "Grove City",
        city: "Grove City",
        state: "OH",
        postalCode: "43123",
        latitude: 39.881,
        longitude: -83.093,
        kind: "suburban",
      },
      {
        area: "Hilliard",
        city: "Hilliard",
        state: "OH",
        postalCode: "43026",
        latitude: 40.033,
        longitude: -83.158,
        kind: "suburban",
      },
      {
        area: "Gahanna",
        city: "Gahanna",
        state: "OH",
        postalCode: "43230",
        latitude: 40.019,
        longitude: -82.879,
        kind: "suburban",
      },
      {
        area: "Upper Arlington",
        city: "Upper Arlington",
        state: "OH",
        postalCode: "43221",
        latitude: 40.027,
        longitude: -83.062,
        kind: "suburban",
      },
      {
        area: "Reynoldsburg",
        city: "Reynoldsburg",
        state: "OH",
        postalCode: "43068",
        latitude: 39.955,
        longitude: -82.812,
        kind: "suburban",
      },
      {
        area: "Bexley",
        city: "Bexley",
        state: "OH",
        postalCode: "43209",
        latitude: 39.969,
        longitude: -82.937,
        kind: "suburban",
      },
      {
        area: "Worthington",
        city: "Worthington",
        state: "OH",
        postalCode: "43085",
        latitude: 40.093,
        longitude: -83.018,
        kind: "suburban",
      },
      {
        area: "Pickerington",
        city: "Pickerington",
        state: "OH",
        postalCode: "43147",
        latitude: 39.884,
        longitude: -82.753,
        kind: "suburban",
      },
      {
        area: "Lewis Center",
        city: "Lewis Center",
        state: "OH",
        postalCode: "43035",
        latitude: 40.198,
        longitude: -82.989,
        kind: "suburban",
      },
      {
        area: "New Albany",
        city: "New Albany",
        state: "OH",
        postalCode: "43054",
        latitude: 40.081,
        longitude: -82.808,
        kind: "suburban",
      },
      {
        area: "Canal Winchester",
        city: "Canal Winchester",
        state: "OH",
        postalCode: "43110",
        latitude: 39.843,
        longitude: -82.804,
        kind: "suburban",
      },
      {
        area: "Powell",
        city: "Powell",
        state: "OH",
        postalCode: "43065",
        latitude: 40.158,
        longitude: -83.075,
        kind: "suburban",
      },
      {
        area: "Whitehall",
        city: "Whitehall",
        state: "OH",
        postalCode: "43213",
        latitude: 39.966,
        longitude: -82.885,
        kind: "suburban",
      },
    ],
  },
  {
    name: "Cincinnati",
    areaCode: "513",
    timezone: "America/New_York",
    neighborhoods: [
      {
        area: "Downtown",
        city: "Cincinnati",
        state: "OH",
        postalCode: "45202",
        latitude: 39.101,
        longitude: -84.512,
        kind: "urban",
      },
      {
        area: "Over-the-Rhine",
        city: "Cincinnati",
        state: "OH",
        postalCode: "45202",
        latitude: 39.11,
        longitude: -84.515,
        kind: "urban",
      },
      {
        area: "Clifton",
        city: "Cincinnati",
        state: "OH",
        postalCode: "45220",
        latitude: 39.136,
        longitude: -84.517,
        kind: "urban",
      },
      {
        area: "Hyde Park",
        city: "Cincinnati",
        state: "OH",
        postalCode: "45208",
        latitude: 39.139,
        longitude: -84.442,
        kind: "urban",
      },
      {
        area: "Norwood",
        city: "Norwood",
        state: "OH",
        postalCode: "45212",
        latitude: 39.155,
        longitude: -84.46,
        kind: "urban",
      },
      {
        area: "Covington",
        city: "Covington",
        state: "KY",
        postalCode: "41011",
        latitude: 39.084,
        longitude: -84.508,
        kind: "urban",
        areaCode: "859",
      },
      {
        area: "Newport",
        city: "Newport",
        state: "KY",
        postalCode: "41071",
        latitude: 39.091,
        longitude: -84.489,
        kind: "urban",
        areaCode: "859",
      },
      {
        area: "Oakley",
        city: "Cincinnati",
        state: "OH",
        postalCode: "45209",
        latitude: 39.153,
        longitude: -84.428,
        kind: "suburban",
      },
      {
        area: "Kenwood",
        city: "Cincinnati",
        state: "OH",
        postalCode: "45236",
        latitude: 39.203,
        longitude: -84.377,
        kind: "suburban",
      },
      {
        area: "West Chester",
        city: "West Chester",
        state: "OH",
        postalCode: "45069",
        latitude: 39.336,
        longitude: -84.405,
        kind: "suburban",
      },
      {
        area: "Mason",
        city: "Mason",
        state: "OH",
        postalCode: "45040",
        latitude: 39.31,
        longitude: -84.31,
        kind: "suburban",
      },
      {
        area: "Blue Ash",
        city: "Blue Ash",
        state: "OH",
        postalCode: "45242",
        latitude: 39.232,
        longitude: -84.378,
        kind: "suburban",
      },
      {
        area: "Anderson Township",
        city: "Cincinnati",
        state: "OH",
        postalCode: "45230",
        latitude: 39.079,
        longitude: -84.336,
        kind: "suburban",
      },
      {
        area: "Florence",
        city: "Florence",
        state: "KY",
        postalCode: "41042",
        latitude: 38.999,
        longitude: -84.627,
        kind: "suburban",
        areaCode: "859",
      },
      {
        area: "Fairfield",
        city: "Fairfield",
        state: "OH",
        postalCode: "45014",
        latitude: 39.346,
        longitude: -84.56,
        kind: "suburban",
      },
      {
        area: "Loveland",
        city: "Loveland",
        state: "OH",
        postalCode: "45140",
        latitude: 39.269,
        longitude: -84.264,
        kind: "suburban",
      },
    ],
  },
  {
    name: "Indianapolis",
    areaCode: "317",
    timezone: "America/Indiana/Indianapolis",
    neighborhoods: [
      {
        area: "Downtown",
        city: "Indianapolis",
        state: "IN",
        postalCode: "46204",
        latitude: 39.768,
        longitude: -86.158,
        kind: "urban",
      },
      {
        area: "Mass Ave",
        city: "Indianapolis",
        state: "IN",
        postalCode: "46202",
        latitude: 39.774,
        longitude: -86.146,
        kind: "urban",
      },
      {
        area: "Fountain Square",
        city: "Indianapolis",
        state: "IN",
        postalCode: "46203",
        latitude: 39.752,
        longitude: -86.146,
        kind: "urban",
      },
      {
        area: "Broad Ripple",
        city: "Indianapolis",
        state: "IN",
        postalCode: "46220",
        latitude: 39.87,
        longitude: -86.141,
        kind: "urban",
      },
      {
        area: "Carmel",
        city: "Carmel",
        state: "IN",
        postalCode: "46032",
        latitude: 39.978,
        longitude: -86.118,
        kind: "suburban",
      },
      {
        area: "Fishers",
        city: "Fishers",
        state: "IN",
        postalCode: "46038",
        latitude: 39.957,
        longitude: -85.965,
        kind: "suburban",
      },
      {
        area: "Noblesville",
        city: "Noblesville",
        state: "IN",
        postalCode: "46060",
        latitude: 40.046,
        longitude: -86.008,
        kind: "suburban",
      },
      {
        area: "Zionsville",
        city: "Zionsville",
        state: "IN",
        postalCode: "46077",
        latitude: 39.951,
        longitude: -86.262,
        kind: "suburban",
      },
      {
        area: "Greenwood",
        city: "Greenwood",
        state: "IN",
        postalCode: "46142",
        latitude: 39.614,
        longitude: -86.107,
        kind: "suburban",
      },
      {
        area: "Avon",
        city: "Avon",
        state: "IN",
        postalCode: "46123",
        latitude: 39.763,
        longitude: -86.4,
        kind: "suburban",
      },
      {
        area: "Brownsburg",
        city: "Brownsburg",
        state: "IN",
        postalCode: "46112",
        latitude: 39.843,
        longitude: -86.398,
        kind: "suburban",
      },
      {
        area: "Castleton",
        city: "Indianapolis",
        state: "IN",
        postalCode: "46250",
        latitude: 39.906,
        longitude: -86.055,
        kind: "suburban",
      },
      {
        area: "Keystone",
        city: "Indianapolis",
        state: "IN",
        postalCode: "46240",
        latitude: 39.916,
        longitude: -86.106,
        kind: "suburban",
      },
      {
        area: "Speedway",
        city: "Speedway",
        state: "IN",
        postalCode: "46224",
        latitude: 39.793,
        longitude: -86.248,
        kind: "suburban",
      },
      {
        area: "Plainfield",
        city: "Plainfield",
        state: "IN",
        postalCode: "46168",
        latitude: 39.704,
        longitude: -86.399,
        kind: "suburban",
      },
      {
        area: "Lawrence",
        city: "Lawrence",
        state: "IN",
        postalCode: "46226",
        latitude: 39.839,
        longitude: -86.025,
        kind: "suburban",
      },
      {
        area: "Westfield",
        city: "Westfield",
        state: "IN",
        postalCode: "46074",
        latitude: 40.043,
        longitude: -86.128,
        kind: "suburban",
      },
    ],
  },
  {
    name: "Chicago",
    areaCode: "312",
    timezone: "America/Chicago",
    neighborhoods: [
      {
        area: "The Loop",
        city: "Chicago",
        state: "IL",
        postalCode: "60603",
        latitude: 41.879,
        longitude: -87.628,
        kind: "urban",
      },
      {
        area: "River North",
        city: "Chicago",
        state: "IL",
        postalCode: "60654",
        latitude: 41.892,
        longitude: -87.634,
        kind: "urban",
      },
      {
        area: "Lincoln Park",
        city: "Chicago",
        state: "IL",
        postalCode: "60614",
        latitude: 41.922,
        longitude: -87.649,
        kind: "urban",
        areaCode: "773",
      },
      {
        area: "Wicker Park",
        city: "Chicago",
        state: "IL",
        postalCode: "60622",
        latitude: 41.909,
        longitude: -87.677,
        kind: "urban",
        areaCode: "773",
      },
      {
        area: "Lakeview",
        city: "Chicago",
        state: "IL",
        postalCode: "60657",
        latitude: 41.94,
        longitude: -87.654,
        kind: "urban",
        areaCode: "773",
      },
      {
        area: "Hyde Park",
        city: "Chicago",
        state: "IL",
        postalCode: "60615",
        latitude: 41.794,
        longitude: -87.594,
        kind: "urban",
        areaCode: "773",
      },
      {
        area: "Logan Square",
        city: "Chicago",
        state: "IL",
        postalCode: "60647",
        latitude: 41.923,
        longitude: -87.707,
        kind: "urban",
        areaCode: "773",
      },
      {
        area: "Evanston",
        city: "Evanston",
        state: "IL",
        postalCode: "60201",
        latitude: 42.045,
        longitude: -87.688,
        kind: "suburban",
        areaCode: "847",
      },
      {
        area: "Oak Park",
        city: "Oak Park",
        state: "IL",
        postalCode: "60302",
        latitude: 41.885,
        longitude: -87.784,
        kind: "suburban",
        areaCode: "708",
      },
      {
        area: "Naperville",
        city: "Naperville",
        state: "IL",
        postalCode: "60540",
        latitude: 41.75,
        longitude: -88.153,
        kind: "suburban",
        areaCode: "630",
      },
      {
        area: "Schaumburg",
        city: "Schaumburg",
        state: "IL",
        postalCode: "60173",
        latitude: 42.033,
        longitude: -88.083,
        kind: "suburban",
        areaCode: "847",
      },
      {
        area: "Skokie",
        city: "Skokie",
        state: "IL",
        postalCode: "60077",
        latitude: 42.034,
        longitude: -87.733,
        kind: "suburban",
        areaCode: "847",
      },
      {
        area: "Oak Brook",
        city: "Oak Brook",
        state: "IL",
        postalCode: "60523",
        latitude: 41.85,
        longitude: -87.951,
        kind: "suburban",
        areaCode: "630",
      },
      {
        area: "Orland Park",
        city: "Orland Park",
        state: "IL",
        postalCode: "60462",
        latitude: 41.63,
        longitude: -87.854,
        kind: "suburban",
        areaCode: "708",
      },
      {
        area: "Northbrook",
        city: "Northbrook",
        state: "IL",
        postalCode: "60062",
        latitude: 42.127,
        longitude: -87.829,
        kind: "suburban",
        areaCode: "847",
      },
      {
        area: "Aurora",
        city: "Aurora",
        state: "IL",
        postalCode: "60504",
        latitude: 41.761,
        longitude: -88.32,
        kind: "suburban",
        areaCode: "630",
      },
      {
        area: "Arlington Heights",
        city: "Arlington Heights",
        state: "IL",
        postalCode: "60005",
        latitude: 42.088,
        longitude: -87.981,
        kind: "suburban",
        areaCode: "847",
      },
      {
        area: "Downers Grove",
        city: "Downers Grove",
        state: "IL",
        postalCode: "60515",
        latitude: 41.809,
        longitude: -88.011,
        kind: "suburban",
        areaCode: "630",
      },
      {
        area: "Wheaton",
        city: "Wheaton",
        state: "IL",
        postalCode: "60187",
        latitude: 41.866,
        longitude: -88.107,
        kind: "suburban",
        areaCode: "630",
      },
      {
        area: "Evergreen Park",
        city: "Evergreen Park",
        state: "IL",
        postalCode: "60805",
        latitude: 41.721,
        longitude: -87.702,
        kind: "suburban",
        areaCode: "708",
      },
    ],
  },
];
